{
 "title": "FAI",
 "description": "Sample dashboard for Folkets AI.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "login_unique_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DAU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "login_dau", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total users over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "expr": "login_unique_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Assistants per model",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(model) (assistant_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conversations per assistant",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(assistant) (conversation_count))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}