services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - skynet
    volumes:
      - redis_data:/data

  worker:
    build: .
    depends_on:
      - redis
    networks:
      - skynet
    volumes:
      - ${PWD}:/home/appuser
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    restart: always
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "9181:9181"
    networks:
      - skynet

networks:
  skynet:

volumes:
  redis_data:
