name: TESTING - Build and push docker image to github registry.

on:
  push:
    branches:
      - cicd/deploy-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./fai-rag-app/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/helsingborg-stad/f-ai:deploy-testing
          no-cache: true
          build-args: GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
