name: Deploy to Jelastic LABS.

on:
  push:
    branches:
      - feat/simpel-redis-queue-test

jobs:
  build-be:
    if: contains(github.event.head_commit.message, 'BE')
    runs-on: codebuild-f-ai-builder-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-medium

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Deploy BACKEND to Elastx
        uses: helsingborg-stad/build-deploy-elastx/1.0@main
        with:
          JELASTIC_API_KEY: ${{ secrets.JELASTIC_API_KEY }}
          JELASTIC_NODE_ID: ${{ vars.JELASTIC_LABS_BE_NODE_ID }}
          JELASTIC_ENV_NAME: ${{ vars.JELASTIC_LABS_ENV_NAME }}
          JELASTIC_TAG: sha-${{ github.sha }}
          DOCKER_CONTEXT: ${{ vars.DOCKER_LABS_BE_CONTEXT }}
          DOCKER_FILE_PATH: ${{ vars.DOCKER_LABS_BE_FILE_PATH }}

  build-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Deploy WORKER to Elastx
        uses: helsingborg-stad/build-deploy-elastx/1.0@main
        with:
          JELASTIC_API_KEY: ${{ secrets.JELASTIC_API_KEY }}
          JELASTIC_NODE_ID: ${{ vars.JELASTIC_LABS_WORKER_NODE_ID }}
          JELASTIC_ENV_NAME: ${{ vars.JELASTIC_LABS_ENV_NAME }}
          JELASTIC_TAG: sha-${{ github.sha }}
          DOCKER_CONTEXT: ${{ vars.DOCKER_LABS_WORKER_CONTEXT }}
          DOCKER_FILE_PATH: ${{ vars.DOCKER_LABS_WORKER_FILE_PATH }}
