name: TESTING - Build and push docker image to github registry.

on:
  push:
    branches:
      - cicd/deploy-testing

jobs:
  build:
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver: "docker"

      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./fai-rag-app/
          platforms: linux/amd64
          file: ./fai-rag-app/Dockerfile.base
          push: ${{ github.event_name != 'pull_request' }}
          tags: helsingborg-stad/fai-rag-app:base
          build-args: GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Clean up Docker images and volumes
        run: |
          docker system prune --all --force --volumes
